father(shivaji,manish).
father(shivaji,anush).
father(krishna,anmol).
father(pashupati,barsha).
father(badri,subham).
father(badri,aakash).
father(ganesh,shivaji).
father(ganesh,pashupati).
father(ganesh,krishna).
father(ganesh,badri).
father(ganesh,radhika).
father(ganesh,laxmi).
father(ganesh,sabitri).
father(ganesh,sumita).
mother(radhika,manish).
mother(radhika,anush).
mother(sabitri,anmol).
mother(laxmi,barsha).
mother(sumita,aakash).
mother(sumita,subham).
mother(balshova,shivaji).
mother(balshova,krishna).
mother(balshova,pashupati).
mother(balshova,badri).
mother(balshova,radhika).
mother(balshova,sabitri).
mother(balshova,laxmi).
mother(balshova,sumita).
parent(X,Y):-father(X,Y).
parent(X,Y):=mother(X,Y).
grandparent(X,Y):-parent(X,Z).parent(Z,Y).
sibling(X,Y):-parent(Z,X).parent(Z,Y).
